In [7]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0, 100, (10, 5)), columns=list('ABCDE'))
display(df)

    A   B   C   D   E
0  11  38   0  15  52
1  51  61  30  38  11
2  55   2  44  35  56
3  88  45  35  28  80
4  86  48   1  60   4
5  15  61  93  94   0
6  95  23  58  47  29
7  38  11  81  24  60
8   8  36  82  76  96
9  45  22  23  40  53

In [4]:
df.rename(mapper=lambda x: str(x)+' Product', axis=1)

   A Product  B Product  C Product  D Product  E Product
0         66         11         39         41         69
1         19         55         54          0         10
2         63         19         26         17          8
3          6         21         65         76         85
4         61         51          5         12         37
5          3         97         27         55          6
6         48         38         52         27         36
7         27         12         32         60         27
8         65         90         30         76          0
9         51         17         33         90         39

In [10]:
dic={
    'A': 'A Product',
    'B': 'B Product',
    'C': 'C Product',   
    'D': 'D Product',
    'E': 'E Product'
}
df =df.rename(columns=dic)
display(df)

   A Product  B Product  C Product  D Product  E Product
0         11         38          0         15         52
1         51         61         30         38         11
2         55          2         44         35         56
3         88         45         35         28         80
4         86         48          1         60          4
5         15         61         93         94          0
6         95         23         58         47         29
7         38         11         81         24         60
8          8         36         82         76         96
9         45         22         23         40         53

In [15]:
df = pd.DataFrame(np.random.randint(0, 100, (5, 4)), columns=list('ABCD'))
display(df)

    A   B   C   D
0  58  84  37  38
1  81  21  63  61
2  69   8  45  21
3   7  82  96  36
4   7  42  70  70

In [19]:
df = df.astype(object).replace({37: "hello", 38: "world"})
display(df)

    A   B      C      D
0  58  84  hello  world
1  81  21     63     61
2  69   8     45     21
3   7  82     96     36
4   7  42     70     70