In [15]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(0, 100, (10, 5)), columns=list('ABCDE'))

df.loc[2] = df.loc[6]
df.loc[3] = df.loc[5]
df.loc[8] = df.loc[7]
df.loc[2,'A'] = 100
display(df)
#display(df.duplicated(keep='last', subset=list('BCDE')))
df = df.drop_duplicates(keep='last', subset=list('BCDE'))
display(df)

     A   B   C   D   E
0   61  86  39  49  62
1   93   9  67  59  93
2  100  74  46  26  95
3   47  51  37  14  84
4   89  47  21  57  32
5   47  51  37  14  84
6   72  74  46  26  95
7   74  74  29  61  21
8   74  74  29  61  21
9   60  71  96  23  97

    A   B   C   D   E
0  61  86  39  49  62
1  93   9  67  59  93
4  89  47  21  57  32
5  47  51  37  14  84
6  72  74  46  26  95
8  74  74  29  61  21
9  60  71  96  23  97

In [11]:
condition = df.duplicated(keep='last', subset=list('BCDE'))
display(condition)
df.loc[condition]
#condition = condition - 1
display(df.loc[(condition-1).astype(bool)])

0    False
1    False
2     True
3     True
4    False
5    False
6    False
7     True
8    False
9    False
dtype: bool

    A   B   C   D   E
0  94   8  88   7  83
1  45  49  82  66  71
4  74  68  11  68  43
5   6  11  19   4  85
6  96  13  22   8  20
8  87  92  95  89  89
9  33  83  67   0  65

In [13]:
exp_index = df.loc[condition].index
df = df.drop(index=exp_index)
display(df)

    A   B   C   D   E
0  94   8  88   7  83
1  45  49  82  66  71
4  74  68  11  68  43
5   6  11  19   4  85
6  96  13  22   8  20
8  87  92  95  89  89
9  33  83  67   0  65

In [21]:
df = pd.DataFrame(np.random.randint(0, 100, (10, 5)), columns=list('ABCDE'))
df = df.sort_values(by=['B','A'], ascending=True)
df = df.sort_index(ascending=False)
display(df)

    A   B   C   D   E
9  45  28  38  92  20
8  86  75  44  78   1
7  62  80  50  17  50
6  80  62  82  39  75
5  95  66  55  21  62
4  78  50  35  28  87
3  49   1  69  63   8
2  19  22   4  14  99
1  67  14  42  32  52
0  16   8  55   9  47

In [33]:
df.sample(n=3, axis=0)

    A   B   C   D   E
2  19  22   4  14  99
1  67  14  42  32  52
4  78  50  35  28  87

In [43]:
index = np.random.randint(0,10,3)
display(index)
display(df.take(index))

array([5, 7, 8], dtype=int32)

    A   B   C   D   E
4  78  50  35  28  87
2  19  22   4  14  99
1  67  14  42  32  52

In [45]:
df
df.set_index('A', inplace=True)
display(df)

     B   C   D   E
A
45  28  38  92  20
86  75  44  78   1
62  80  50  17  50
80  62  82  39  75
95  66  55  21  62
78  50  35  28  87
49   1  69  63   8
19  22   4  14  99
67  14  42  32  52
16   8  55   9  47

In [50]:
df.reset_index()
#display(df)
df = df.reindex(labels=['B','C'], axis=1)
display(df)

        B   C
A  B
45 28 NaN  38
86 75 NaN  44
62 80 NaN  50
80 62 NaN  82
95 66 NaN  55
78 50 NaN  35
49 1  NaN  69
19 22 NaN   4
67 14 NaN  42
16 8  NaN  55

In [51]:
df = df.droplevel(level=-1, axis=0)
display(df)

     B   C
A
45 NaN  38
86 NaN  44
62 NaN  50
80 NaN  82
95 NaN  55
78 NaN  35
49 NaN  69
19 NaN   4
67 NaN  42
16 NaN  55