In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("penguins.csv", sep=',')
display(df)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [8]:
df = pd.read_table("people.txt", sep=' ', names=["Name", "Age", "Gender"])
display(df)

   Name  Age Gender
0  lucy   19     北京
1  mery   20     上海
2   tom   22     北京

In [13]:
df = pd.read_csv("people.txt", sep=r'\s+', names=["Name", "Age", "Gender"])
display(df)

   Name  Age Gender
0  lucy   19     北京
1  mery   20     上海
2   tom   22     北京

In [26]:
df = pd.read_excel("Excel02.xlsx", header=None, names=["Name", "Age", "City"], sheet_name=0)
df.to_csv("Excel03_output.csv")
display(df)

   Name  Age City
0  lucy   19   北京
1  mery   20   上海
2   tom   21   深圳

In [32]:
fp = open("Excel03_output.csv", "r", encoding="utf-8", errors="ignore")
df = pd.read_csv(fp,  sep=',', names=["Name", "Age", "Gender"])
display(df)

     Name  Age Gender
NaN  Name  Age   City
0.0  lucy   19     北京
1.0  mery   20     上海
2.0   tom   21     深圳

In [36]:
df = pd.DataFrame(
    np.random.randint(0, 10000, size=(10000, 4)),
    columns=["A", "B", "C", "D"]
)
display(df)
df.describe(percentiles=[.25, .5, .75,0.9, 0.95,0.99])

         A     B     C     D
0     6142  1983  3918  8143
1     8646  1418  5067  8814
2     3910  8192  8614  9791
3     8925  1591  7268  4713
4     2625   879  9151  4042
...    ...   ...   ...   ...
9995  8390  4881  9930  2507
9996  1539  1835  5958  1477
9997  5044   481  5522  7854
9998  8559  5502  3115  9121
9999  3092  1245  5002  1149

[10000 rows x 4 columns]

                  A             B             C             D
count  10000.000000  10000.000000  10000.000000  10000.000000
mean    4943.025700   5015.532800   4998.465000   4973.639400
std     2899.209225   2849.085945   2928.858208   2901.778571
min        1.000000      0.000000      0.000000      2.000000
25%     2392.750000   2575.000000   2446.000000   2442.000000
50%     4919.500000   5029.000000   4984.500000   4954.000000
75%     7436.000000   7459.250000   7540.000000   7485.000000
90%     8968.300000   8981.100000   9105.100000   9011.100000
95%     9492.100000   9479.050000   9561.000000   9517.050000
99%     9900.000000   9892.010000   9921.000000   9908.010000
max     9999.000000   9998.000000   9998.000000   9999.000000

In [37]:
df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       10000 non-null  int32
 1   B       10000 non-null  int32
 2   C       10000 non-null  int32
 3   D       10000 non-null  int32
dtypes: int32(4)
memory usage: 156.4 KB

In [38]:
df.head(10)

      A     B     C     D
0  6142  1983  3918  8143
1  8646  1418  5067  8814
2  3910  8192  8614  9791
3  8925  1591  7268  4713
4  2625   879  9151  4042
5  5601  8382  9277   611
6  1084  6125  2354  2436
7  3923  6752  9688  4130
8   109  1429  2386  1260
9   985  4120  9951  6957

In [39]:
df.tail(10)

         A     B     C     D
9990  6612  8870  7222  8140
9991  6378  1149  1193  7675
9992  7777  3472   215  9341
9993  3007  5776  6519  5672
9994  3826  6609  5894  6112
9995  8390  4881  9930  2507
9996  1539  1835  5958  1477
9997  5044   481  5522  7854
9998  8559  5502  3115  9121
9999  3092  1245  5002  1149

In [40]:
type(None)

NoneType

In [41]:
type(np.nan)

float

In [52]:
def get_sum(x):
    return x.sum()

data1 = np.arange(10000000, dtype=object)
%timeit get_sum(data1)

data2 = np.arange(10000000, dtype=np.float64)
%timeit get_sum(data2)

682 ms ± 122 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
31.3 ms ± 7.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [57]:
df = pd.DataFrame(np.random.randint(0,10, size= (5,2)), columns=list('AB'))
display(df)
df.loc[2] = None
display(df)

   A  B
0  0  9
1  5  9
2  1  6
3  0  1
4  7  4

     A    B
0  0.0  9.0
1  5.0  9.0
2  NaN  NaN
3  0.0  1.0
4  7.0  4.0

In [60]:
df.loc[2,'A']

np.float64(nan)

In [65]:
l_data=[None, 1,2,3,3,3.14]
arr = np.array(l_data, dtype=object)
display(arr)
display(pd.Series(data=arr, dtype=pd.Float64Dtype()))

array([None, 1, 2, 3, 3, 3.14], dtype=object)

0    <NA>
1     1.0
2     2.0
3     3.0
4     3.0
5    3.14
dtype: Float64

In [134]:
df = pd.DataFrame(np.random.random(size= (10,4)), columns=list('ABCD'))
#display(df)
df.loc[2] = np.nan
df.loc[4,'B'] = np.nan
df.loc[5,'D'] = np.nan
df.loc[9, ['A','B']] = np.nan
display(df)
#display(df.mean())
#display(df.mean(axis=1))
#df = df.ffill(axis=1)
#display(df)
###
#df1 = df.T.copy()
#display(df1)
#df1.fillna(value=df1.mean(), inplace=True)
#display(df1)
#df = df1.T.copy()
#display(df)
####

#df.fillna(value=df.mean())

          A         B         C         D
0  0.809687  0.508345  0.501451  0.601838
1  0.462013  0.380948  0.518680  0.774758
2       NaN       NaN       NaN       NaN
3  0.176488  0.117023  0.762517  0.275139
4  0.302167       NaN  0.367359  0.317353
5  0.231122  0.075242  0.177188       NaN
6  0.816307  0.911210  0.211818  0.592346
7  0.737832  0.040387  0.790878  0.428164
8  0.184494  0.563899  0.072604  0.653977
9       NaN       NaN  0.954355  0.519626

In [155]:
display(df.dropna(axis=1, how='all', subset=['B','C']))

KeyError: ['B', 'C']

In [118]:
df.dropna(axis=0, how='any')

          A         B         C         D
0  0.003341  0.984723  0.884823  0.589558
1  0.670783  0.675002  0.884699  0.335857
3  0.949087  0.840160  0.332958  0.765651
6  0.006412  0.869707  0.794748  0.129159
7  0.674588  0.900117  0.427046  0.045396
8  0.167035  0.947440  0.709987  0.514586

In [116]:
display(df.notnull().any(axis=1))
display(df.loc[df.notnull().any(axis=1)])
display(df['D'].notnull())
display(df.loc[df['D'].notnull()])

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7     True
8     True
9     True
dtype: bool

          A         B         C         D
0  0.781207  0.785699  0.083215  0.832214
1  0.867461  0.146514  0.118725  0.751323
3  0.371841  0.061854  0.310311  0.510813
4  0.140258       NaN  0.302761  0.024044
5  0.522085  0.507688  0.423513       NaN
6  0.624676  0.150135  0.229114  0.417536
7  0.206656  0.767048  0.374942  0.668327
8  0.478231  0.068961  0.407718  0.213749
9       NaN       NaN  0.812382  0.062656

0     True
1     True
2    False
3     True
4     True
5    False
6     True
7     True
8     True
9     True
Name: D, dtype: bool

          A         B         C         D
0  0.781207  0.785699  0.083215  0.832214
1  0.867461  0.146514  0.118725  0.751323
3  0.371841  0.061854  0.310311  0.510813
4  0.140258       NaN  0.302761  0.024044
6  0.624676  0.150135  0.229114  0.417536
7  0.206656  0.767048  0.374942  0.668327
8  0.478231  0.068961  0.407718  0.213749
9       NaN       NaN  0.812382  0.062656

In [112]:
display(df.loc[df.isnull().all(axis=1)])

    A   B   C   D
2 NaN NaN NaN NaN

In [70]:
df.isnull()

       A      B      C      D
0  False  False  False  False
1  False  False  False  False
2   True   True   True   True
3  False  False  False  False
4  False   True  False  False
5  False  False  False   True
6  False  False  False  False
7  False  False  False  False
8  False  False  False  False
9   True   True  False  False

In [74]:
display(df.isnull().any())

A    True
B    True
C    True
D    True
dtype: bool

In [75]:
display(df.isnull().any(axis=1))

0    False
1    False
2     True
3    False
4     True
5     True
6    False
7    False
8    False
9     True
dtype: bool

In [73]:
display(np.array([True, False, True, False]).any(axis=0))
display(np.array([True, False, True, False]).all(axis=0))

np.True_

np.False_

In [ ]:
display(df.loc[df.isnull().any(axis=1)])

          A        B         C         D
2       NaN      NaN       NaN       NaN
4  0.358711      NaN  0.567467  0.342697
5  0.790316  0.00556  0.848495       NaN
9       NaN      NaN  0.454077  0.287609

In [79]:
display(df.loc[:, df.isnull().any()])

          A         B         C         D
0  0.550134  0.171183  0.395095  0.335492
1  0.237451  0.413798  0.834406  0.200281
2       NaN       NaN       NaN       NaN
3  0.913286  0.342726  0.788724  0.099262
4  0.358711       NaN  0.567467  0.342697
5  0.790316  0.005560  0.848495       NaN
6  0.490003  0.483788  0.083282  0.896343
7  0.174752  0.215714  0.985523  0.939517
8  0.734405  0.546800  0.384584  0.388409
9       NaN       NaN  0.454077  0.287609

In [82]:
display(df.notnull().all(axis=0))
display(df.notnull().all(axis=1))
df.loc[df.notnull().all(axis=1)]

A    False
B    False
C    False
D    False
dtype: bool

0     True
1     True
2    False
3     True
4    False
5    False
6     True
7     True
8     True
9    False
dtype: bool

          A         B         C         D
0  0.550134  0.171183  0.395095  0.335492
1  0.237451  0.413798  0.834406  0.200281
3  0.913286  0.342726  0.788724  0.099262
6  0.490003  0.483788  0.083282  0.896343
7  0.174752  0.215714  0.985523  0.939517
8  0.734405  0.546800  0.384584  0.388409

In [84]:
df.isnull()
df.isnull().mean()

A    0.2
B    0.3
C    0.1
D    0.2
dtype: float64

In [86]:
df.fillna(0)

          A         B         C         D
0  0.550134  0.171183  0.395095  0.335492
1  0.237451  0.413798  0.834406  0.200281
2  0.000000  0.000000  0.000000  0.000000
3  0.913286  0.342726  0.788724  0.099262
4  0.358711  0.000000  0.567467  0.342697
5  0.790316  0.005560  0.848495  0.000000
6  0.490003  0.483788  0.083282  0.896343
7  0.174752  0.215714  0.985523  0.939517
8  0.734405  0.546800  0.384584  0.388409
9  0.000000  0.000000  0.454077  0.287609