In [5]:
import numpy as np
import pandas as pd
arr1 = np.random.randint(0, 100, size=10)
display(arr1)

array([34, 79, 60,  0,  5, 47, 52, 16, 94, 36], dtype=int32)

In [6]:
display(pd.Series(arr1))

0    34
1    79
2    60
3     0
4     5
5    47
6    52
7    16
8    94
9    36
dtype: int32

In [7]:
s2 = pd.Series(data=arr1, index=[f'idx{i}' for i in range(len(arr1))])
display(s2)

idx0    34
idx1    79
idx2    60
idx3     0
idx4     5
idx5    47
idx6    52
idx7    16
idx8    94
idx9    36
dtype: int32

In [10]:
l1 = [1,2,3,4]
l1[0] = 5
s3 = pd.Series(l1, index=list('ABCD'))

In [13]:
display(s3)

A    5
B    2
C    3
D    4
dtype: int64

In [12]:
l1[1]=100

In [14]:
user_info = {
    'name': 'John Doe',
    'age': 30,
    'email': 'johndoe@example.com',
    'address': '123 Main St'
}
display(pd.Series(user_info))

name                  John Doe
age                         30
email      johndoe@example.com
address            123 Main St
dtype: object

In [15]:
pd.Series(data = user_info, index=['A', 'B', 'C', 'address'])

A                  NaN
B                  NaN
C                  NaN
address    123 Main St
dtype: object

In [26]:
s5 = pd.Series(data = user_info, index=[ 'name', 'address'])
display(s5["name"])

'John Doe'

In [18]:
index = list('ABCDE')
s4 = pd.Series(data=6, index=index)
display(s4)

A    6
B    6
C    6
D    6
E    6
dtype: int64

In [22]:
display(s4.name)
s4.A
s4['A']

None

np.int64(6)

In [32]:
s6 = pd.Series(data = [1,2,3], index=list('ABC'), name='MySeries')
display(s6.name)
display(s6.shape)
display(s6.index)
display(s6.values)
display(s6.ndim)
display(s6.dtype)
display(s6.size)

'MySeries'

(3,)

Index(['A', 'B', 'C'], dtype='str')

array([1, 2, 3])

1

dtype('int64')

3

In [34]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

list1 = [1,2,3,'name']
s1 = pd.Series(data=list1)
display(s1)
display(s1.dtype)

0       1
1       2
2       3
3    name
dtype: object

dtype('O')

In [35]:
data = np.random.randint(0,100, size = (3,4))
index = ['tom','jerry','mike']
columns = ['Chinese','Math','English','Physics']
df = pd.DataFrame(data=data, index=index, columns=columns)
display(df)

       Chinese  Math  English  Physics
tom         38     6        1       89
jerry       41    60       32       54
mike        32    65        5       50

In [40]:
names=['tom','jerry','mike', 'alice', 'bob']
Chinese=np.random.randint(0,101, size=5)
Math=np.random.randint(0,101, size=5)
English=np.random.randint(0,101, size=5)
Physics=np.random.randint(0,101, size=5)
Chemistry=np.random.randint(0,101, size=5)
dicts = ({'Name': names, 'Chinese': Chinese, 'Math': Math, 'English': English, 'Physics': Physics, 'Chemistry': Chemistry})
df = pd.DataFrame(data = dicts)
display(df)

    Name  Chinese  Math  English  Physics  Chemistry
0    tom       24    29       93       15         57
1  jerry       15    99       33       65         15
2   mike       33    46       45       92         52
3  alice        3     3       96       65         41
4    bob       88    68        9       32         75

In [41]:
df.dtypes

Name           str
Chinese      int32
Math         int32
English      int32
Physics      int32
Chemistry    int32
dtype: object

In [42]:
df.values

array([['tom', 24, 29, 93, 15, 57],
       ['jerry', 15, 99, 33, 65, 15],
       ['mike', 33, 46, 45, 92, 52],
       ['alice', 3, 3, 96, 65, 41],
       ['bob', 88, 68, 9, 32, 75]], dtype=object)

In [43]:
df.columns

Index(['Name', 'Chinese', 'Math', 'English', 'Physics', 'Chemistry'], dtype='str')

In [44]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [46]:
df = pd.DataFrame(data = np.random.randint(0,101, size=(5,6)), columns=['Chinese', 'Math', 'English', 'Physics', 'Chemistry', 'Biology'])
display(df)
display(df + 10)

   Chinese  Math  English  Physics  Chemistry  Biology
0       27   100       89       64         75       61
1       64    70       75       29         63        9
2       89    54       88       60         89       81
3       41    70       51       26         16       11
4       25    58       72       65         85       96

   Chinese  Math  English  Physics  Chemistry  Biology
0       37   110       99       74         85       71
1       74    80       85       39         73       19
2       99    64       98       70         99       91
3       51    80       61       36         26       21
4       35    68       82       75         95      106

In [47]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
display(df + arr1)

   Chinese  Math  English  Physics  Chemistry  Biology
0       28   102       92       68         80       67
1       65    72       78       33         68       15
2       90    56       91       64         94       87
3       42    72       54       30         21       17
4       26    60       75       69         90      102

In [58]:
arr2 = np.random.randint(0,101, size=(5,6))
display(df + arr2)

   Chinese  Math  English  Physics  Chemistry  Biology
0       94   161      128      109        165       93
1      151   118      100      107        118       24
2      148   129       94       66        102       95
3       87   134       64       32         70       85
4       25   149      114       77         89      140

In [63]:
display(df)
s3 = pd.Series(data = [1,2,3,4,5])
s4 = pd.Series(data = [10, 20, 30, 40, 50,60], index=['Chinese', 'Math', 'English', 'Physics', 'Chemistry', 'Biology'])
display(df.add(s3, axis='index'))
display(df.add(s4, axis='columns'))

   Chinese  Math  English  Physics  Chemistry  Biology
0       27   100       89       64         75       61
1       64    70       75       29         63        9
2       89    54       88       60         89       81
3       41    70       51       26         16       11
4       25    58       72       65         85       96

   Chinese  Math  English  Physics  Chemistry  Biology
0       28   101       90       65         76       62
1       66    72       77       31         65       11
2       92    57       91       63         92       84
3       45    74       55       30         20       15
4       30    63       77       70         90      101

   Chinese  Math  English  Physics  Chemistry  Biology
0       37   120      119      104        125      121
1       74    90      105       69        113       69
2       99    74      118      100        139      141
3       51    90       81       66         66       71
4       35    78      102      105        135      156

In [65]:
arr = np.random.randint(0,10, size=(5,6))
display(arr)
display(arr > 5)

array([[5, 1, 7, 3, 8, 4],
       [6, 6, 0, 8, 0, 0],
       [1, 8, 7, 9, 2, 4],
       [1, 8, 3, 9, 3, 8],
       [3, 1, 8, 0, 3, 5]], dtype=int32)

array([[False, False,  True, False,  True, False],
       [ True,  True, False,  True, False, False],
       [False,  True,  True,  True, False, False],
       [False,  True, False,  True, False,  True],
       [False, False,  True, False, False, False]])

In [76]:
arr2 = np.random.randint(0,10, size=(5,6))
#display(arr2)
df = pd.DataFrame(arr2,  columns=['A', 'B', 'C', 'D', 'E', 'F'])
display(df)
display(df.loc[0, 'A'])
display(df.loc[0])
display(df.loc[:, 'A'])
display(df.loc[1:2, 'B':'C'])

   A  B  C  D  E  F
0  1  9  6  5  4  5
1  2  4  3  2  5  7
2  0  7  1  5  7  3
3  7  9  4  8  9  4
4  0  2  7  3  2  7

np.int32(1)

A    1
B    9
C    6
D    5
E    4
F    5
Name: 0, dtype: int32

0    1
1    2
2    0
3    7
4    0
Name: A, dtype: int32

   B  C
1  4  3
2  7  1

In [77]:
df.loc[[True, True, False, False, True]]

   A  B  C  D  E  F
0  1  9  6  5  4  5
1  2  4  3  2  5  7
4  0  2  7  3  2  7

In [94]:
bool_list = pd.Series(data = np.array([True, True, False, False, False]), index = [0,4,1,2,3])

display(bool_list)

0     True
4     True
1    False
2    False
3    False
dtype: bool

In [96]:
display(df)
display(df.loc[bool_list])

   A  B  C  D  E  F
0  1  9  6  5  4  5
1  2  4  3  2  5  7
2  0  7  1  5  7  3
3  7  9  4  8  9  4
4  0  2  7  3  2  7

   A  B  C  D  E  F
0  1  9  6  5  4  5
4  0  2  7  3  2  7

In [98]:
bool_list2 = pd.Series(data = np.array([True, True, False, False, False, True]))
display(df.loc[:, bool_list2.values])

   A  B  F
0  1  9  5
1  2  4  7
2  0  7  3
3  7  9  4
4  0  2  7

In [102]:
s = pd.Series(data = np.random.randint(0, 10, size=5), index = [0, 1, 2, 3, 4])
display(s)
bool_list = s > 6
display(bool_list)
display(s.loc[bool_list])

0    1
1    4
2    1
3    0
4    7
dtype: int32

0    False
1    False
2    False
3    False
4     True
dtype: bool

4    7
dtype: int32

In [ ]:
display(df)
display(df.iloc[0])

   A  B  C  D  E  F
0  1  9  6  5  4  5
1  2  4  3  2  5  7
2  0  7  1  5  7  3
3  7  9  4  8  9  4
4  0  2  7  3  2  7

A    1
B    9
C    6
D    5
E    4
F    5
Name: 0, dtype: int32

In [112]:
display(df.loc[:, 'A'])
display(df.iloc[:, 0])

0    1
1    2
2    0
3    7
4    0
Name: A, dtype: int32

0    1
1    2
2    0
3    7
4    0
Name: A, dtype: int32

In [114]:
display(df.iloc[0:3])

   A  B  C  D  E  F
0  1  9  6  5  4  5
1  2  4  3  2  5  7
2  0  7  1  5  7  3

In [115]:
display(df.loc[0:2])

   A  B  C  D  E  F
0  1  9  6  5  4  5
1  2  4  3  2  5  7
2  0  7  1  5  7  3

In [121]:
display(df.loc[1, 'B'])
df.loc[2, 'B'] = 10
display(df)

np.int32(4)

   A   B  C  D  E  F
0  1  10  6  5  4  5
1  2   4  3  2  5  7
2  0  10  1  5  7  3
3  7   9  4  8  9  4
4  0   2  7  3  2  7

In [123]:
display(df.loc[:,'B'].iloc[0])

np.int32(10)

In [124]:
display(df['A'])

0    1
1    2
2    0
3    7
4    0
Name: A, dtype: int32

In [125]:
display(df[['A','B']])

   A   B
0  1  10
1  2   4
2  0  10
3  7   9
4  0   2

In [130]:
df = pd.DataFrame(data=np.random.randint(0, 100, size=(5, 4)), columns=['A', 'B', 'C', 'D'])
display(df)

condition = df > 60
display(condition)

df['A'] > 60

    A   B   C   D
0  21  10  13  22
1  54  54  85  37
2  83  81  42  82
3  90   6  47  69
4  28   2  72  37

       A      B      C      D
0  False  False  False  False
1  False  False   True  False
2   True   True  False   True
3   True  False  False   True
4  False  False   True  False

0    False
1    False
2     True
3     True
4    False
Name: A, dtype: bool

In [133]:
df = df.where(df>60,other='bu ji ge')
display(df)

          A         B         C         D
0  bu ji ge  bu ji ge  bu ji ge  bu ji ge
1  bu ji ge  bu ji ge      85.0  bu ji ge
2      83.0      81.0  bu ji ge      82.0
3      90.0  bu ji ge  bu ji ge      69.0
4  bu ji ge  bu ji ge      72.0  bu ji ge

In [138]:
df = pd.DataFrame(data=np.random.randint(0, 100, size=(5, 4)), columns=['A', 'B', 'C', 'D'])
df = df.where(cond = df['A'] < 60, other = pd.Series(data=[100, 200], index=['A', 'B']), axis=1)
display(df)

     A    B     C     D
0   57   44  85.0  82.0
1  100  200   NaN   NaN
2   58   66  16.0  69.0
3   10   76  55.0  27.0
4  100  200   NaN   NaN

In [141]:
df = pd.DataFrame(data=np.random.randint(0, 100, size=(5, 4)), columns=['A', 'B', 'C', 'D'])
df = df.mask(cond = df > 60, other = 'passed')
display(df)

        A       B       C       D
0       5  passed      50      39
1       1  passed      12       6
2      46      40  passed      47
3  passed  passed      41  passed
4  passed  passed  passed  passed

In [147]:
df = pd.DataFrame(data=np.random.randint(0, 100, size=(5, 4)), columns=['A', 'B', 'C', 'D'])
display(df)
display(df.query('A > 60 and B > 60'))

    A   B   C   D
0  24  32  79  75
1  63  71  18  21
2  70  13  46  61
3  30  39  55  35
4  14  22  47  40

    A   B   C   D
1  63  71  18  21

In [152]:
df = pd.DataFrame(data=np.random.randint(0, 100, size=(5, 4)), columns=['A', 'B', 'C', 'D'])
display(df)
df.columns = ['AA', 'BB', 'CC', 'DD']
display(df)

display(df.filter(items=['AA', 'BB']))
display(df.filter(items=[0, 1],axis=0))

    A   B   C   D
0  66  93  75  77
1  22  53  40  22
2  52   4  83  89
3  85  99  96  39
4   2  60  75  46

   AA  BB  CC  DD
0  66  93  75  77
1  22  53  40  22
2  52   4  83  89
3  85  99  96  39
4   2  60  75  46

   AA  BB
0  66  93
1  22  53
2  52   4
3  85  99
4   2  60

   AA  BB  CC  DD
0  66  93  75  77
1  22  53  40  22

In [153]:
df = pd.DataFrame(data=np.random.randint(0, 100, size=(5, 4)), columns=['A', 'B', 'C', 'D'])
display(df)
df.columns = ['AA', 'BB', 'CB', 'DB']
display(df.filter(regex='B', axis=1))

    A   B   C   D
0  85  53  63  92
1  58  73  11  70
2  37  16   1  56
3  65  24  70  26
4  43  75  40  94

   BB  CB  DB
0  53  63  92
1  73  11  70
2  16   1  56
3  24  70  26
4  75  40  94

In [181]:
df = pd.DataFrame(data=np.random.randint(0, 100, size=(5, 4)), columns=['A', 'B', 'C', 'D'])
display(df)
df.iloc[1,1] = np.nan
display(df.sum(axis=0))
display(df.sum(axis=1))
display(df.values)
display(np.nansum(df.values))
display(df.sum().sum())
#print("==="*50)

    A   B   C   D
0  31  67  11  95
1  60  69  89   4
2  21  66  15   2
3  10   9  72  42
4  46  88  10  33

A    168.0
B    230.0
C    197.0
D    176.0
dtype: float64

0    204.0
1    153.0
2    104.0
3    133.0
4    177.0
dtype: float64

array([[31., 67., 11., 95.],
       [60., nan, 89.,  4.],
       [21., 66., 15.,  2.],
       [10.,  9., 72., 42.],
       [46., 88., 10., 33.]])

np.float64(771.0)

np.float64(771.0)

In [194]:
index = ['张三', '李四', '王五', '赵六']
columns = ['Python', 'Java', 'C++']
score1 = pd.DataFrame(data=np.random.randint(40, 100, size=(4, 3)), index=index, columns=columns)
display(score1)
score1.loc['张三','Java']= 0
score1.loc['李四'] = score1.loc['李四'] + 10
display(score1)

score2 = pd.DataFrame(data=np.random.randint(40, 100, size=(4, 3)), index=index, columns=columns)
display(score2)
score2 += 10
display(score2)

bool_list = score2['Python'] > score2['Java']
display(bool_list)
display(score2.loc[bool_list])
display(score2.loc[bool_list].index)


score_total = score1 + score2
display(score_total/2)

    Python  Java  C++
张三      79    40   56
李四      43    79   92
王五      44    46   63
赵六      54    65   48

    Python  Java  C++
张三      79     0   56
李四      53    89  102
王五      44    46   63
赵六      54    65   48

    Python  Java  C++
张三      81    90   85
李四      41    51   62
王五      80    64   60
赵六      92    51   83

    Python  Java  C++
张三      91   100   95
李四      51    61   72
王五      90    74   70
赵六     102    61   93

张三    False
李四    False
王五     True
赵六     True
dtype: bool

    Python  Java  C++
王五      90    74   70
赵六     102    61   93

Index(['王五', '赵六'], dtype='str')

    Python  Java   C++
张三    85.0  50.0  75.5
李四    52.0  75.0  87.0
王五    67.0  60.0  66.5
赵六    78.0  63.0  70.5

In [204]:
df = pd.DataFrame(data=np.random.randint(0,10, size=(5,3)), columns = list('ABC'))
#df.index= list('abcde')
#display(df)
m_index = pd.RangeIndex(start = 0, stop =5, step=1, name='index')
display(m_index)
df.index = m_index
display(df)

pd.CategoricalIndex(data=[1,2,3,4])

RangeIndex(start=0, stop=5, step=1, name='index')

       A  B  C
index
0      4  0  0
1      3  3  0
2      2  6  0
3      7  3  5
4      8  7  8

CategoricalIndex([1, 2, 3, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')

In [217]:
LEVEL1=["Period 1", "Period 2"]
LEVEL2 = ['A','B','C']
import pandas as pd
columns = pd.MultiIndex.from_product([LEVEL1, LEVEL2], names=['Period', 'Product'])
display(columns)

MultiIndex([('Period 1', 'A'),
            ('Period 1', 'B'),
            ('Period 1', 'C'),
            ('Period 2', 'A'),
            ('Period 2', 'B'),
            ('Period 2', 'C')],
           names=['Period', 'Product'])

In [218]:
index = pd.Index(data=["lucy", "tom", "alex"], name = "sellers")
data = np.random.randint(0, 10, size=(3, 6))
df = pd.DataFrame(data=data, index=index, columns=columns)
display(df)

Period  Period 1       Period 2
Product        A  B  C        A  B  C
sellers
lucy           4  5  1        5  5  7
tom            3  5  1        6  9  6
alex           6  2  1        4  0  8

KeyError: 'A'

In [212]:
index = pd.MultiIndex.from_product([["Period 1", "Period 2"], ["lucy", "tom", "alex"]],names=['Period', 'Seller'])
columns = pd.Index(data=['A', 'B', 'C'], name='Product')
data = np.random.randint(0, 10, size=(6, 3))
df = pd.DataFrame(data=data, index=index, columns=columns)
display(df)

Product          A  B  C
Period   Seller
Period 1 lucy    4  9  5
         tom     3  8  7
         alex    2  2  4
Period 2 lucy    8  4  9
         tom     6  0  2
         alex    2  4  2

In [213]:
display(df.index)

MultiIndex([('Period 1', 'lucy'),
            ('Period 1',  'tom'),
            ('Period 1', 'alex'),
            ('Period 2', 'lucy'),
            ('Period 2',  'tom'),
            ('Period 2', 'alex')],
           names=['Period', 'Seller'])

In [215]:
tuples =pd.MultiIndex.from_tuples([('Period 1', 'lucy'),
            ('Period 1',  'tom'),
            ('Period 1', 'alex'),
            ('Period 2', 'lucy'),
            ('Period 2',  'tom'),
            ('Period 2', 'alex')],
           names=['Period', 'Seller'])
index = list('ABC')
data = np.random.randint(0, 100, size=(3,6))
df = pd.DataFrame(data=data, index = index, columns=tuples)
display(df)

Period Period 1          Period 2
Seller     lucy tom alex     lucy tom alex
A            84  72   68       33  24   66
B            20  45   55       58  84   22
C            90  94   52       37  49   79

In [231]:
columns=[['Period 1','Period 1','Period 1','Period 2','Period 2','Period 2'],['lucy','tom','alex','lucy','tom','alex']]
index=list('ABC')
data = np.random.randint(0, 100, size=(3,6))
df = pd.DataFrame(data=data, index=index, columns=pd.MultiIndex.from_arrays(columns, names=['Period', 'Seller']))
display(df)

Period Period 1          Period 2
Seller     lucy tom alex     lucy tom alex
A             5  87    3       54  18   41
B             3  86   45       61  80   40
C            26  82   31       70  86   77

In [229]:
display(df.columns)
display(df.index)

MultiIndex([('Period 1', 'lucy'),
            ('Period 1',  'tom'),
            ('Period 1', 'alex'),
            ('Period 2', 'lucy'),
            ('Period 2',  'tom'),
            ('Period 2', 'alex')],
           names=['Period', 'Seller'])

Index(['A', 'B', 'C'], dtype='str')

In [226]:
df.loc[:, pd.IndexSlice[:, 'lucy']]

Period Period 1 Period 2
Seller     lucy     lucy
A            50       78
B            68        5
C            69       57

In [230]:
display(df)

Period Period 1          Period 2
Seller     lucy tom alex     lucy tom alex
A            50  94   98       78  22   95
B            68  53   77        5  79   71
C            69  90   32       57  96    3

In [239]:
df.index
df.iloc[0:2]

Period Period 1          Period 2
Seller     lucy tom alex     lucy tom alex
A             5  87    3       54  18   41
B             3  86   45       61  80   40

In [1]:
import pandas as pd
import numpy as np

# 行索引：期数 + 销售员
index = pd.MultiIndex.from_product(
    [["第一期", "第二期"], ["alex", "lucy", "tom"]],
    names=["期数", "销售员"]
)

# 按图片中的顺序填写销售数据
data = np.random.randint(0,100,size=(6,3))

df = pd.DataFrame(data, index=index, columns=["A", "B", "C"])
df.columns.name = "产品名称"

display(df)

产品名称       A   B   C
期数  销售员
第一期 alex  18  12  93
    lucy  99  87  62
    tom   80  87  65
第二期 alex  47  15  98
    lucy  68  53  37
    tom   41  70  62

In [2]:
df.unstack()

产品名称    A             B             C
销售员  alex lucy tom alex lucy tom alex lucy tom
期数
第一期    18   99  80   12   87  87   93   62  65
第二期    47   68  41   15   53  70   98   37  62

In [3]:
df.stack()

期数   销售员   产品名称
第一期  alex  A       18
           B       12
           C       93
     lucy  A       99
           B       87
           C       62
     tom   A       80
           B       87
           C       65
第二期  alex  A       47
           B       15
           C       98
     lucy  A       68
           B       53
           C       37
     tom   A       41
           B       70
           C       62
dtype: int32